# 作用：配置web ui demoProject相关的运行参数。

# [servers]
# web_host = http://www.baidu.com

# [isInit]
# # 项目名=1   进行初始化
# # 项目名=0   不进行初始化
# init = 1
[servers]
web_host = https://www.saucedemo.com

[isInit]
init = 0
